language: node_js
node_js:
  - 14.17.3
sudo: required
script:
  - yarn build
deploy:
  provider: heroku
  app: depp4
  api_key:
    secure: Je7+MftMATqaYd+5gkMwcCfuLn9dV1FmE+FR2p0T6EOxb4LuhdkR/Kb+cbK+fzBNgArMEEegZYL6WHtJQ2m77KTLuuqrsEqVIRo6UJFu1kcgMjm9bxa6cV0uyErXWXXFxDCZxqhY7J4BWeYyAvpRpbQjXMyCno+Va2amJHu7eCHQl1koBXJgliUoS5CpzuFLX4+jHfLpkh24DxkYRyV03yR8kLKF80ZGO5Zd94OcS6GKzSadQk+Wi5o9Dlhaa/HJLjC9VBYL06shtnvk0eVbdLV4Ir4ildt5zDkFJIUkK4LwfiuVUObkFhegAQqNfRVv0+GcJO2TnJyfr3riCkRbe4ivwkpFy9mC62WCpAvS9otn+VWttzvnGNM6cNb06R+D4ldSxX4qrEELP/hkhvOco84lm4Ltjxm3DnVDP4yWPkcqPLkjuGRb59pMYStr4mRw0ZinMPTSKOF4fu9dGI/SD5xePw2Twpngsez61q3jyHOVaVwyDpqoVl6UC/xZyyxV2JpDsND6DWBlAzzMOY5Flah1z3PTQva3sBXFcM9aniRDWIYopNyZ/HKkxLYqTH9Ctis13BEXXA0xSslKW5xHEHR/MnBtD8nNLF8X0loEhjKt3D7g+0NyENSCQZ3/FWy4Y93kJJtyuin2E5JPuTcx7BzgmnMANdI7OXzV2/Wx5Vs=
  on:
    repo: vinisp/mysite
    branch: main
